version: '3'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # initializes db using dbsetup.sh
      - ./:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  redis:
    image: redis:5.0.5-alpine

  pinger:
    build:
      context: ../../..
      dockerfile: deploy/docker/local/Dockerfile
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      - tail
      - "-f"
      - "/dev/null"  # makes the container run indefinitely
    volumes:
      - ../../..:/src
    depends_on:
      - redis
      - db

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - redis
      - db 
      - adminer
    command: redis:${REDIS_PORT} adminer:${ADMINER_PORT}
